<?php

/**
 * BaseMusic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property string $url
 * @property string $image
 * @property boolean $is_active
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method string      getUrl()         Returns the current record's "url" value
 * @method string      getImage()       Returns the current record's "image" value
 * @method boolean     getIsActive()    Returns the current record's "is_active" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Music       setUserId()      Sets the current record's "user_id" value
 * @method Music       setTitle()       Sets the current record's "title" value
 * @method Music       setDescription() Sets the current record's "description" value
 * @method Music       setUrl()         Sets the current record's "url" value
 * @method Music       setImage()       Sets the current record's "image" value
 * @method Music       setIsActive()    Sets the current record's "is_active" value
 * @method Music       setUser()        Sets the current record's "User" value
 * 
 * @package    api
 * @subpackage model
 * @author     Vladimir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMusic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('music');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'builder' => 
             array(
              0 => 'tsDoctrineInflector',
              1 => 'urlize',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}