rest:
  class:   sfObjectRouteCollection
  options:
    model:   music
    actions: [ create, delete, list, update ]
    module:  rest
    column:  id
    format:  json

#default rules
homepage:
  url:   /
  param: { module: api, action: index }
#
#default:
#  url:   /:module/:action/*
