# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

all:
  is_secure : false
  info:
    is_secure : true
  permissions : [ read , write ]