<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfoauthserveruserscope extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_oauth_server_user_scope', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'consumer_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_oauth_server_user_scope');
    }
}