<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmusic extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('music', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'music_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('music');
    }
}