<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfoauthserveraccesstoken extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_oauth_server_access_token', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'token' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 40,
             ),
             'secret' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 40,
             ),
             'consumer_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 8,
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 256,
             ),
             'expires' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'protocole' => 
             array(
              'type' => 'integer',
              'default' => 1,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_oauth_server_access_token');
    }
}