<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfoauthserverdeveloper extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_oauth_server_developer', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'consumer_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'admin' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_oauth_server_developer');
    }
}