<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfoauthserverconsumer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_oauth_server_consumer', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'consumer_key' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 40,
             ),
             'consumer_secret' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 40,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 256,
             ),
             'description' => 
             array(
              'type' => 'text',
              'notnull' => true,
              'length' => NULL,
             ),
             'protocole' => 
             array(
              'type' => 'integer',
              'default' => 1,
              'length' => 8,
             ),
             'base_domain' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'callback' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 256,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_oauth_server_consumer');
    }
}